name: RSS to Telegram Advanced

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python libs
        run: pip install feedparser pillow requests

      - name: Run bot
        run: python bot.py
